
== Algorithms

Once the heterogenous list is created, algorithms are required to do some actions. like for example, to add new element to existing list, or to retrieve an element, or remove specific entry in the list like or even sorting the types in the list. Just like data structure `std::vector<>` (note that `std::vector<>` can be used to hold the values of homogenous type at runtime).

These algorithms can be used with any list of types like std::tuple<>. It is *not* restricted to `ctl::list` alone.
To use any algorithms make sure to add `#include <container/algorithms.hpp>` in source file.

All algorithms will result in `new type`. *original type is never modified*

=== Modifiers

Set of algorithms are used to get the `new list` from the `original list` by adding/removing one or more types. 

General usage of the algorithm is:
[source, cpp]
using modified_type = _algo name_<L<Ts...>, U>::type

where,

* _ algo name _ => name of the modifiable algorithms listed below
* L<Ts...> => list which has to be modified
* U => type of the interest. It could be single type or another list type! This is optional parameter depending on algorithm.
* `::type` => to access the type from the result of the modified list. If algorithm name is postfixed with `_t` then there is no need of using `::type`

Following are some of `modifiable` algorithms (replaced with _ algo name _):

==== rename

Usage:
[source, cpp]
using result = ctl::rename<L<Ts...>, Y>::type

if `L<Ts...> = ctl::list<T1, T2, T3>` and `Y == std::tuple` then `result = std::tuple<T2, T3, T1>`

Variants:

* `rename`
* `rename_t` => to avoid `::type`

==== apply

Usage:
[source, cpp]
using result = ctl::apply<Y, L<Ts...>>::type

if `Y == std::tuple` and `L<Ts...> = ctl::list<T1, T2, T3>` then `result = std::tuple<T2, T3, T1>`

Variants:

* `apply` => same as `rename` but template parameters reversed
* `apply_t` => to avoid `::type`

==== rotate left

Usage:
[source, cpp]
using result = rotate_left_c<L<Ts...>, _num_>::type

if `L<Ts...> = L<T1, T2, T3>` and `_num_ = 1` then `result = L<T2, T3, T1>`

Variants:

* `rotate_left_c`
* `rotate_left_c_t` => to avoid `::type`
* `rotate_left` => `_num_` is passed as type (It should have `::value` to access the member). `::type` is needed to access the type
* `rotate_left_t` => to avoid `::type`

==== rotate right

Usage:
[source, cpp]
using result = rotate_right_c<L<Ts...>, _num_>::type

if `L<Ts...> = L<T1, T2, T3>` and `_num_ = 1` then `result = L<T3, T1, T2>`

Variants:

* `rotate_right_c`
* `rotate_right_c_t` => to avoid `::type`
* `rotate_right` => `_num_` is passed as type (It should have `::value` to access the member). `::type` is needed to access the result type
* `rotate_right_t` => to avoid `::type`

==== sort

Usage:
[source, cpp]
using result = sort<L<Ts...>>::type

if `L<Ts...> = L<T3, T2, T1>` then `result = L<T1, T2, T3>` when `T1::value <= T2::value <= T3::value`. Logic used here is `Quick sort`.

Variants:

* `sort`
* `sort_t` => to avoid `::type`
* `sort_p` => to provide comparator as predicate to compare 2 types. `::type` is needed to access the result type
** `comparator` should return `true` if the first template parameter should be considered before the second template parameter
* `sort_p_t` => to avoid `::type`
* `sort_qmf_p` => to provide comparator predicate as quoted meta function. `::type` is needed to access the result type
* `sort_qmf_p_t` => to avoid `::type`

==== reverse

Usage:
[source, cpp]
using result = ctl::reverse<L<Ts...>>::type

if `L<Ts...> = L<T1, T2, T3>` then `result = L<T3, T2, T1>`

Variants:

* `reverse`
* `reverse_t` => to avoid `::type`

==== replace

Usage:
[source, cpp]
using result = ctl::replace<L<Ts...>, TR, RW>::type

if `L<Ts...> = L<T1, T2, T3>`, `TR = T2` and `RW = T4` then `result = L<T1, T4, T3>`

Variants:

* `replace`
* `replace_t` => to avoid `::type`
* `replace_at_c` => to replace type at given position (position is a constant). `::type` is needed to access the result type
* `replace_at_c_t` => to avoid `::type`
* `replace_at` => to replace type at given position (position is a type, `::value` is used to access the constant). `::type` is needed to access the result type
* `replace_at_t` => to avoid `::type`
* `replace_if` => to replace all types which results in `true` when passed to given predicate. `::type` is needed to access the result type
* `replace_if_t` => to avoid `::type`
* `replace_if_qmf` => predicate passed as quoted meta function. `::type` is needed to access the result type
* `replace_if_qmf_t` => to avoid `::type`

==== push_front

Usage:
[source, cpp]
using result = ctl::push_front<L<Ts...>, T>::type

if `L<Ts...> = L<T1, T2, T3>` and `L<T4, T5, T6>` then `result = L<T4, T5, T6, T1, T2, T3>`

Variants:

* `push_front` => to push another `type/list` to front of given list
* `push_front_t` => used to avoid `::type`

==== push_back

Usage:
[source, cpp]
using result = ctl::push_back<L<Ts...>, T>::type

if `L<Ts...> = L<T1, T2, T3>` and `L<T4, T5, T6>` then `result = L<T1, T2, T3, T4, T5, T6>`

Variants:

* `push_back` => to push another `type/list` to back of given list
* `push_back_t` => to avoid `::type`

==== append

Usage:
[source, cpp]
using result = ctl::append<L<Ts...>, T>::type

if `L<Ts...> = L<T1, T2, T3>` and `L<T4, T5, T6>` then `result = L<T1, T2, T3, T4, T5, T6>`

Variants:

* `append` => alias to `push_back`
* `append_t` => alias to `push_back_t`

==== pop_front

Usage:
[source, cpp]
using result = ctl::pop_front<L<Ts...>>::type

if `L<Ts...> = L<T1, T2, T3>` then `result = L<T2, T3>`
if list provided is empty, then it will result in error

Variants:

* `pop_front`
* `pop_front_t` => to avoid `::type`

==== pop_back

Usage:
[source, cpp]
using result = ctl::pop_back<L<Ts...>>::type

if `L<Ts...> = L<T1, T2, T3>` then `result = L<T1, T2>`

Variants:

* `pop_back`
* `pop_back_t` => to avoid `::type`

==== insert

Usage:
[source, cpp]
using result = ctl::insert_c<L<Ts...>, _index_, Us...>::type

if `L<Ts...> = L<T1, T2, T3>`, `_index_ = 1` and `Us... = U1, U2, U3`  then `result = L<T1, U1, U2, U3, T2, T3>`.
if _index_ should be less than size of the `L<Ts...>`. otherwise it will result in compiler error

Variants:

* `insert_c`
* `insert_c_t` => to avoid `::type`
* `insert` => when _index_ passed as type (`::value` is used to get the index value). `::type` is needed to access the result type
* `insert_t` => to avoid `::type`

==== repeat

Usage:
[source, cpp]
using result = ctl::repeat_c<L<Ts...>, _count_>::type

if `L<Ts...> = L<T1, T2, T3>` and _count_ = 2 then `result = L<T1, T2, T3, T1, T2, T3>`.
if _count_ == 0, then `result = L<>`

Variants:

* `repeat_c`
* `repeat_c_t` => to avoid `::type`
* `repeat` => when _count_ passed as type (`::value` is used to get the count value). `::type` is needed to access the result type
* `repeat_t` => to avoid `::type`

==== clear

Usage:
[source, cpp]
using result = ctl::repeat_c<L<Ts...>>::type

if `L<Ts...> = L<T1, T2, T3>` then `result = L<>`

Variants:

* `clear`
* `clear_t` => to avoid `::type`

==== erase

Usage:
[source, cpp]
using result = ctl::erase_c<L<Ts...>, _pos1_, _pos2_>::type

if `L<Ts...> = L<T1, T2, T3>`, _pos1_ == 0 and _pos2_ == 1 then `result = L<T2, T3>`.
if condition _pos1_ < `L<Ts...>` <= _pos2_ fails, then results in compiler error.

Variants:

* `erase_c`
* `erase_c_t` => to avoid `::type`
* `erase` => when _pos1_ and _pos2_ are passed a types. `::type` is needed to access the result type
* `erase_t` => to avoid `::type`

==== remove

Usage:
[source, cpp]
using result = ctl::remove_type<L<Ts...>, U>::type

if `L<Ts...> = L<T1, T2, T3>` and `U = T2` then `result = L<T1, T2>`.

Variants:

* `remove_type`
* `remove_type_t` => to avoid `::type`
* `remove_if` => when `U` is a predicate. if `P<T>` results in `true` then type is removed. `::type` is needed to access the result type
* `remove_if_t` => to avoid `::type`
* `remove_if_qmf`
* `remove_if_qmf_t`

==== filter

Usage:
[source, cpp]
using result = ctl::filter_if<P, L1, L2, ..., Ln>::type

if `L1<T1, T2, T3>, L2<T4, T5, T6> ... Ln<Tn, Tn+1, Tn+2>` and `P<T2, T5, ..., Tn+1> = true` then `result = L<T2>`.

Variants:

* `filter_if`
* `filter_if_t` => to avoid `::type`
* `filter_if_qmf` => when predicate is passed as quoted meta function. `::type` is needed to access the result type
* `filter_if_qmf_t` => to avoid `::type`

==== copy_if

Usage:
[source, cpp]
using result = ctl::copy_if<L<Ts...>, P>::type

if `L<Ts...> = L<T1, T2, T3>` and `P<T2> = true` then `result = L<T2>`.

Variants:

* `copy_if` => alias to `filter_if`
* `copy_if_t` => to avoid `::type`
* `copy_if_qmf` => alias to `filter_if_qmf`
* `copy_if_qmf_t` => to avoid `::type`

==== drop

Usage:
[source, cpp]
using result = ctl::drop_c<L<Ts...>, _count_>::type

if `L<Ts...> = L<T1, T2, T3>` and _count_ = 2 then `result = L<T3>`. 
if _count_ >= `L<Ts...>` size, then `result = L<>`

Variants:

* `drop_c`
* `drop_c_t` => to avoid `::type`
* `drop` => when _count_ is a type. `::type` is needed to access the result type
* `drop_t` => to avoid `::type`

==== remove_duplicates

Usage:
[source, cpp]
using result = ctl::remove_duplicates<L<Ts...>>::type

if `L<Ts...> = L<T1, T1, T2>` and _count_ = 2 then `result = L<T1, T2>`. 

Variants:

* `remove_duplicates`
* `remove_duplicates_t` => to avoid `::type`

==== unique

Usage:
[source, cpp]
using result = ctl::unique<L<Ts...>>::type

if `L<Ts...> = L<T1, T1, T2>` and _count_ = 2 then `result = L<T1, T2>`. 

Variants:

* `unique` => alias to `remove_duplicates`
* `unique_t` => to avoid `::type`

==== unique_if

Usage:
[source, cpp]
using result = ctl::unique_if<L<Ts...>, P>::type

if `L<Ts...> = L<T1, T2, T3>` and `P<T> = T2` then `result = L<T1, T2>`.

Variants:

* `unique_if` => alias to `remove_if`
* `unique_if_t` => to avoid `::type`
* `unique_if_qmf` => alias to `remove_if_qmf`
* `unique_if_qmf_t` => to avoid `::type`

==== transform

Usage:
[source, cpp]
using result = ctl::transform<F, L1, L2, ..., Ln>::type

if `L1<T1, T2, T3>, L2<T4, T5, T6> ... Ln<Tn, Tn+1, Tn+2>` then `result = L<F<T1, T4, ..., Tn>, F<T2, T5, ..., Tn+1>, F<T3, T6, ..., Tn+2>>`. F is templated type.

Variants:

* `transform`
* `transform_t` => to avoid `::type`
* `transform_qmf` => when `F` is provided as quoted meta function. `::type` is needed to access the result type
* `transform_qmf_t` => to avoid `::type`
* `transform_if` => when predicate `P` is passed as 3rd template argument. `result` will have `F<T>` only when `P<T>` is `true`. `::type` is needed to access the result type
* `transform_if_t` => to avoid `::type`
* `transform_if_qmf` => when `F` and predicate provided as quoted meta function
* `transform_if_qmf_t` => to avoid `::type`

=== Accessors

Set of algorithms are used to retrieve the one or more types from the `original list`. In some case `conditional retrieval` is possible. *These algorithms will result in compiler error if the provided `list` is empty*. 

General usage of the algorithm is:
[source, cpp]
using result = _algo name_<L<Ts...>, P>::type

where,

* _ algo name _ => name of the accessor algorithms listed below
* L<Ts...> => list from which one or more type is retrieved
* P => `predicate/function` which is `applied on each type` to access/retrieve. It is `optional`, not every algorithm needs this parameter
* `::type` => to access the type from the result. If algorithm name is postfixed with `_t` then there is no need of using `::type`

Following are some of `accessor` algorithms (replaced with _ algo name _):

==== at

Usage:
[source, cpp]
using result = ctl::at_c<L<Ts...>, _pos_>::type

if `L<Ts...> = L<T1, T2, T3>` and _pos_ == 2 then `result = T3`. if condition _pos_ < size of `L<Ts...>` then it will result in compiler error

Variants:

* `at_c`
* `at_c_t` => to avoid `::type`
* `at` => when _pos_ is passed as type. `::type` is needed to access the result type
* `at_t` => to avoid `::type`

==== first

Usage:
[source, cpp]
using result = ctl::first<L<Ts...>>::type

if `L<Ts...> = L<T1, T2, T3>` then `result = T1`. if list provided is empty, then it will result in compiler error

Variants:

* `first` => to get the first type from the list
* `first_t` => to avoid `::type`

==== front

Usage:
[source, cpp]
using result = ctl::front<L<Ts...>>::type

if `L<Ts...> = L<T1, T2, T3>` then `result = T1`. if list provided is empty, then it will result in compiler error

Variants:

* `front` => alias to `first`
* `front_t` => to avoid `::type`

==== last

Usage:
[source, cpp]
using result = ctl::last<L<Ts...>>::type

if `L<Ts...> = L<T1, T2, T3>` then `result = T3`. if list provided is empty, then it will result in compiler error

Variants:

* `last` => to get the last type from the list
* `last_t` => to avoid `::type`

==== back

Usage:
[source, cpp]
using result = ctl::back<L<Ts...>>::type

if `L<Ts...> = L<T1, T2, T3>` then `result = T3`. if list provided is empty, then it will result in compiler error

Variants:

* `back` => alias to `last`
* `back_t` => to avoid `::type`

==== head

Usage:
[source, cpp]
using result = ctl::head<L<Ts...>>::type

if `L<Ts...> = L<T1, T2, T3>` then `result = L<T1, T2>`. if list provided is empty, then it will result in compiler error. If there is only one entry in the list, then `result = L<>`

Variants:

* `head`
* `head_t` => to avoid `::type`

==== tail

Usage:
[source, cpp]
using result = ctl::tail<L<Ts...>>::type

if `L<Ts...> = L<T1, T2, T3>` then `result = L<T2, T3>`. if list provided is empty, then it will result in compiler error. If there is only one entry in the list, then `result = L<>`

Variants:

* `tail`
* `tail_t` => to avoid `::type`

==== take

Usage:
[source, cpp]
using result = ctl::take<L<Ts...>, _count_>::type

if `L<Ts...> = L<T1, T2, T3>` and _count_ = 2, then `result = L<T1, T2>`. if _count_ >= size of `L<Ts...>` then `result = L<Ts...>`

Variants:

* `take_c`
* `take_c_t` => to avoid `::type`
* `take` => when _count_ is provided as type. `::type` is needed to access the result type
* `take_t` => to avoid `::type`


=== Miscellaneous

Set of algorithms used for miscellaneous stuffs which are not listed above! Name of the algorithm will give hint on misc stuff.

Following are some of algorithms:

==== size

Usage:
[source, cpp]
using result = ctl::size<L<Ts...>>::type

if `L<Ts...> = L<T1, T2, T3>` then `result = std::integral_constant<uint32_t, 3>`

Variants:

* `size`
* `size_t` => to avoid `::type`

==== count

Usage:
[source, cpp]
using result = ctl::count<L<Ts...>>::type

if `L<Ts...> = L<T1, T2, T3>` then `result = std::integral_constant<uint32_t, 3>`

Variants:

* `count` => alias to `size`
* `count_t` => to avoid `::type`
* `count_if` => when `predicate P` is passed as second template argument. type will be counted only if `P<T> is true`. `::type` is needed to access the result type
* `count_if_t` => to avoid `::type`
* `count_if_qmf` => when `predicate` is passed as quoted meta function
* `count_if_qmf_t` => to avoid `::type`

==== empty

Usage:
[source, cpp]
using result = ctl::empty<L<Ts...>>::type

if `L<Ts...> = L<T1, T2, T3>` then `result = std::false_type`. if `L<Ts...> = L<>` then `result = std::true_type`

Variants:

* `empty`
* `empty_t` => to avoid `::type`

==== contains

Usage:
[source, cpp]
using result = ctl::contains<L<Ts...>, U>::type

if `L<Ts...> = L<T1, T2, T3>` and `U == T2` then `result = std::true_type`. if `U == T4` then `result = std::false_type`

Variants:

* `contains`
* `contains_t` => to avoid `::type`

==== find

Usage:
[source, cpp]
using result = ctl::find<L<Ts...>, U>::type

if `L<Ts...> = L<T1, T2, T3>` and `U == T2` then `result = std::integral_constant<uint32_t, 1>`. if `U` is not found in list, then `result` is size of the list

Variants:

* `find`
* `find_t` => to avoid `::type`
* `find_if` => when `U` is a predicate. `result` will have the first position for which `P<T>` will result in `true`. `::type` is needed to access the result type
* `find_if_t` => to avoid `::type`
* `find_if_qmf` => when predicate is passed as quoted meta function. `::type` is needed to access the result type
* `find_if_qmf_t` => to avoid `::type`

==== all_of

Usage:
[source, cpp]
using result = ctl::all_of<L<Ts...>, P>::type

if `L<Ts...> = L<T1, T2, T3>` and `P<T> == true` for all T1, T2, T3 types then `result = std::true_type`, otherwise `result = std::false_type`.

Variants:

* `all_of`
* `all_of_t` => to avoid `::type`
* `all_of_qmf` => when predicate is passed as quoted meta function. `::type` is needed to access the result type
* `all_of_qmf_t` => to avoid `::type`

==== any_of

Usage:
[source, cpp]
using result = ctl::any_of<L<Ts...>, P>::type

if `L<Ts...> = L<T1, T2, T3>` and `P<T> == true` for any T1, T2, T3 types then `result = std::true_type`, otherwise `result = std::false_type`.

Variants:

* `any_of`
* `any_of_t` => to avoid `::type`
* `any_of_qmf` => when predicate is passed as quoted meta function. `::type` is needed to access the result type
* `any_of_qmf_t` => to avoid `::type`

==== none_of

Usage:
[source, cpp]
using result = ctl::none_of<L<Ts...>, P>::type

if `L<Ts...> = L<T1, T2, T3>` and `P<T> == false` for all T1, T2, T3 types then `result = std::true_type`, otherwise `result = std::false_type`.

Variants:

* `none_of`
* `none_of_t` => to avoid `::type`
* `none_of_qmf` => when predicate is passed as quoted meta function. `::type` is needed to access the result type
* `none_of_qmf_t` => to avoid `::type`

==== from integer sequence

Usage:
[source, cpp]
using result = ctl::from_integer_sequence<sequence, RT>::type

if `sequence = std::integer_sequence<unsigned int, 9, 2, 5>` and `RT == ctl::list` then `result = ctl::list<std::integral_constant<unsigned int, 9>, std::integral_constant<unsigned int, 2>, std::integral_constant<unsigned int, 5> >`

`RT` default type is `std::tuple`.

Variants:

* `from_integer_sequence`
* `from_integer_sequence_t` => to avoid `::type`

==== iota

Usage:
[source, cpp]
using result = ctl::iota_c<_count_, DT, RT>::type

if _count_ = 3, `DT = uint32_t` and `RT == ctl::list` then `result = ctl::list<std::integral_constant<uint32_t, 0>, std::integral_constant<uint32_t, 1>, std::integral_constant<uint32_t, 2> >`

`DT` default type is `uint32_t`.
`RT` default type is `std::tuple`.

* `iota_c`
* `iota_c_t` => to avoid `::type`
* `iota` => when _count_ is provided as type. `::type` is needed to access the result type
* `iota_t` => to avoid `::type`
