= CTL (Compile Time Library)

This is a C++ library, created to include algorithms that can be worked out at compile time.
It uses C++ template meta programming and functional programming techniques to execute many algorithms at compile time on one or more types. 

_The more work done at compile time, less time to complete the job at run time!_

All algorithms/features are wrapped in ```namespace *ctl*```

Features available to use:

* link:/container/container.adoc[container]
* link:/utility.adoc[utility]

*Note:*

* Container algorithms and utility are influenced by https://www.boost.org/doc/libs/1_80_0/libs/mp11/doc/html/mp11.html#list[Boost::MP11]. This has been started as re-inventing wheel theory and used personal approach to implement the same MP11 library, many of the algorithms are having the same name as mentioned in library MP11.
* `_t` next to algorithm name is implemented to avoid using with `::type` keyword every time algorithm is used
* `_c` next to algorithm name is implemented to take constants which are known at compile time (ex: true/false or numbers)
* `_f` next to algorithm name is implemented to take template types as template arguments
* `_p` next to algorithm name is implemented to take predicate as template parameter (predicate is a template type). It is same as `_f`, but `_p` is used to make it more precise
* `_qmf` next to algorithm name is implemented to take Quoted meta functions as template arguments
**  `_qmf` implementations are usually using its counter parts from *non `_qmf`* counterparts
