name: Build and Unit Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DEFAULT_CXX_STANDARD: 20
  DEFAULT_LLVM_VERSION: 17
  DEFAULT_GCC_VERSION: 12
  CMAKE_GENERATOR: Ninja
  DEBIAN_FRONTEND: noninteractive

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang, gcc]
        version: [12, 13]
        cxx_standard: [20]
        stdlib: [libstdc++, libc++]
        build_type: [Debug]
        include:
          - compiler: gcc
            toolchain_root: "/usr"
            cxx_flags: ""
          - version: 13
            compiler: gcc
            install: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt update && sudo apt-get install -y gcc-13 g++-13
            cc: "gcc-13"
            cxx: "g++-13"
          - version: 12
            compiler: gcc
            install: sudo apt update && sudo apt install -y gcc-12
            cc: "gcc-12"
            cxx: "g++-12"
            cxx_flags: ""

    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: |
          ${{ matrix.install }}
          sudo apt install -y ninja-build

      - name: Configure CMake
        env:
          CC: ${{matrix.toolchain_root}}/bin/${{matrix.cc}}
          CXX: ${{matrix.toolchain_root}}/bin/${{matrix.cxx}}
        run: cmake -B ${{github.workspace}}/build -DCMAKE_CXX_STANDARD=${{matrix.cxx_standard}} -DCMAKE_CXX_FLAGS_INIT=${{matrix.cxx_flags}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

      - name: Build Unit Tests
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} -v -t all

      - name: Test
        working-directory: ${{github.workspace}}/build/test
        run: ctest -j $(nproc) -C ${{matrix.build_type}}
